vich_uploader:
    db_driver: orm
    mappings:
       user_image:
           uri_prefix: '%AVATAR_BASEPATH%'
           upload_destination: '%kernel.project_dir%/public/%AVATAR_BASEPATH%'
           #namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
           namer:
               service: vich_uploader.namer_hash
               options: { algorithm: 'md5' }
           inject_on_load: true
           delete_on_update: true
           delete_on_remove: true
    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
    #        namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
